#!/bin/bash
set -eu -o pipefail
shopt -s nullglob

: ${PULLDIR:=/var/lib/rheapdumps}

prefix=$1

while read host; do
	hostdir=${prefix}incoming/$host

	ec=0
	rsync -aq --remove-source-files $host:$PULLDIR/ $hostdir || ec=$?

	if [[ $ec -ne 0 ]]; then
		echo "rsync exited with code $ec" >&2
		continue
	fi

	for src in $hostdir/*; do
		filename=${host}_$(basename $src)
		dest=$prefix$filename

		ec=0
		mv $src $dest || ec=$?

		if [[ $ec -ne 0 ]]; then
			echo "Could not move $src to $dest: $ec" >&2
			continue
		fi

		ec=0
		chmod 644 $dest || ec=$?

		if [[ $ec -ne 0 ]]; then
			echo "Could not chmod 644 $dest: $ec" >&2
		fi
	done
done
