#!/bin/bash -e

#apt install moreutils

systemctl disable --now filepuller \
	remotefilewatch@{bootstrap-testnet,validator-0{1..5}}.rchain-dev.tk || true

install -CD -m644 sysusers.conf /etc/sysusers.d/rheapdumps.conf
install -CD -m644 tmpfiles.conf /etc/tmpfiles.d/rheapdumps.conf
install -CD -m700 -o rheapdumps -d /etc/rheapdumps/ssh
install -CD -m755 -t /opt/rheapdumps {remotefilewatch,filepuller}{,.daemon}
install -CD -m644 *.service -t /etc/systemd/system

systemd-sysusers /etc/sysusers.d/rheapdumps.conf
systemd-tmpfiles --create /etc/tmpfiles.d/rheapdumps.conf

systemctl daemon-reload

systemctl enable --now filepuller \
	remotefilewatch@{bootstrap-testnet,validator-0{1..5}}.rchain-dev.tk
